#!/bin/sh
LOGTAG="firstboot-network"

if uci -q get network.lan >/dev/null 2>&1; then
    echo "[$LOGTAG] configuring network..."
    uci batch <<EOF
set network.lan.ipaddr='192.168.1.2'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.1.1'
add_list network.lan.dns='192.168.1.1'
EOF
    uci commit network
    /etc/init.d/network reload >/dev/null 2>&1
    logger -t "$LOGTAG" "network configured: IP=192.168.1.2 DNS=192.168.1.1"
else
    logger -t "$LOGTAG" "network.lan not found, skipping"
fi

exit 0

